### PR TITLE
Updates recipe to the latest release

### PR DESCRIPTION
**Pull request by anjos**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR just updates this package to the latest release.

### CODE REVIEW

**Comment by anjos** [comment]
@conda-forge-admin please pre-render

**Comment by anjos** [comment]
@conda-forge-admin please rerender

**Comment by anjos** [comment]
@thewchan ready for review.

**Comment by bskinn** [comment]
To be explicit: I am ok with being added as a maintainer on this feedstock.

**Comment by thewchan** [comment]
@anjos Thank you to your hard work at making this work and thanks to @beckermr for helping! @bskinn  I can add you as maintainer

**Comment by thewchan** [comment]
Oh oops looks like you have already been added @bskinn

**Pull request merged**
